export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";
export const RESET = "RESET";
export const TEST = "TEST";

export const USER_FETCH_REQUEST = "USER_FETCH_REQUEST";
export const USER_FETCH_ERROR = "USER_FETCH_ERROR";

export const USER_FETCH_SUCCESS = "USER_FETCH_SUCCESS";
export const USER_CREATE_SUCCESS = "USER_CREATE_SUCCESS";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_DELETE_SUCCESS = "USER_DELETE_SUCCESS";